---
title: "Statistical Learning"
author: "Saryu Patel"
date: "12/3/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(glmnet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(11)
```

## Lasso

Predicting birthweight

```{r}
bwt_df <- 
  read_csv("data/birthweight.csv") %>% 
  mutate(
    babysex = as.factor(babysex),
    babysex = fct_recode(babysex, "male" = "1", "female" = "2"),
    frace = as.factor(frace),
    frace = fct_recode(frace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4", "other" = "8"),
    malform = as.logical(malform),
    mrace = as.factor(mrace),
    mrace = fct_recode(mrace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4")
  ) %>% 
  sample_n(200)
```

```{r}
x <- model.matrix(bwt ~ ., bwt_df)[,-1]
y <- bwt_df$bwt
```

Fit lasso.

```{r}
lambda_grid <- 10 ^ seq(3, -2, -0.1)

lasso_fit <- glmnet(x, y, lambda = lambda_grid)

lasso_cv <- cv.glmnet(x, y, lambda = lambda_grid)

lambda_opt <- lasso_cv$lambda.min
```

Visualize what we did.

```{r}
lasso_fit %>% 
  broom::tidy() %>% 
  complete(term, lambda, fill = list(estimate = 0)) %>% 
  filter(term != "(Intercept)") %>% 
  ggplot(aes(x = log(lambda), y = estimate, group = term, color = term)) +
  geom_path() +
  geom_vline(xintercept = log(lambda_opt))
```

Plot CV curve.

```{r}
lasso_cv %>% 
  broom::tidy() %>% 
  ggplot(aes(x = log(lambda), y = estimate)) + 
  geom_point()  
```

Optimal model:

```{r}
lasso_fit_opt <- 
  glmnet(x, y, lambda = lambda_opt)

lasso_fit_opt %>% broom::tidy()
```

